services:
  app:
    image: 807091918015.dkr.ecr.ap-northeast-2.amazonaws.com/oz/flask:latest
    build: .
    container_name: myapp
    networks:
      - shared-net
    ports:
      - "5001:5000"
    env_file:
      - app.env

networks:
  shared-net:
    external: true
