services:
  app:
    build: .
    container_name: myapp
    networks:
      - shared-net
    ports:
      - "5001:5000"
    environment:
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_PORT: ${MYSQL_PORT}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DB: ${MYSQL_DB}
    # depends_on:
    #   - mysql-db

networks:
  shared-net:
    external: true
